import { SyllabusItem, UserState } from './types';

export const SYLLABUS: SyllabusItem[] = [
  { id: 1, title: "Oração - Nossa fé nos reuniu", scripture: "Hebreus 11,6-12", description: "O início da jornada e a importância da fé." },
  { id: 2, title: "Quem é Deus - A Santíssima Trindade", scripture: "1 João 4,12-16", description: "Pai, Filho e Espírito Santo." },
  { id: 3, title: "Jesus - Quem é o Filho de Deus?", scripture: "João 14,8-11", description: "Conhecendo o Salvador." },
  { id: 4, title: "Porque Jesus foi Crucificado - Pecados", scripture: "Lucas 23,33-47", description: "O sacrifício por amor." },
  { id: 5, title: "Ressurreição de Jesus", scripture: "João 20,1-10", description: "A vitória sobre a morte." },
  { id: 6, title: "Segunda Vinda de Jesus", scripture: "Mateus 24,35-39", description: "Jesus voltará? Quando?" },
  { id: 7, title: "Maria, Mãe de Deus", scripture: "João 19, 25-27", description: "A importância de Nossa Senhora." },
  { id: 8, title: "História da Igreja Católica", scripture: "Atos 2,42-47", description: "A fundação e os primeiros passos." },
  { id: 9, title: "Somos Igreja", scripture: "Mateus 16,13-19", description: "Nossa missão como corpo de Cristo." },
  { id: 99, title: "Cerco de Jericó - Participar", scripture: "Josué 6", description: "Evento especial de oração.", isEvent: true, isReview: false },
  { id: 10, title: "Quem é o Espírito Santo?", scripture: "João 14,15-21", description: "O paráclito, o consolador." },
  { id: 11, title: "Eucaristia e Milagres", scripture: "Lucas 22,14-20", description: "O corpo e sangue de Cristo." },
  { id: 12, title: "Missa - Parte a Parte", scripture: "Atos 2,42", description: "Entendendo a celebração." },
  { id: 13, title: "Missa - Dinâmica e Objetos", scripture: "Liturgia", description: "Atividade prática sobre a missa." },
  { id: 101, title: "Revisão e Jogos", scripture: "João 15,15", description: "Revisão das aulas 1-13", isReview: true },
  { id: 102, title: "Prova do Primeiro Módulo", scripture: "João 15,13", description: "Teste seus conhecimentos", isExam: true },
  { id: 14, title: "Sacramentos: Iniciação", scripture: "Mt 28,19; At 8,12-17", description: "Batismo, Crisma e Eucaristia." },
  { id: 15, title: "Sacramentos: Cura", scripture: "João 20,21-23; Tg 5,14-15", description: "Penitência e Unção dos Enfermos." },
  { id: 16, title: "Sacramentos: Serviço", scripture: "2Tm 1,6; Mt 19,6", description: "Ordem e Matrimônio." },
  { id: 17, title: "Bíblia - Antigo Testamento", scripture: "Salmos 119:105", description: "As raízes da nossa fé." },
  { id: 18, title: "Bíblia - Novo Testamento", scripture: "2 Pedro 1,20-21", description: "A Boa Nova de Jesus." },
  { id: 19, title: "10 Mandamentos: 1º, 2º e 3º", scripture: "Ex 34, 27-29", description: "Amar a Deus sobre todas as coisas." },
  { id: 20, title: "10 Mandamentos: 4º e 5º", scripture: "Ex 20,12; Salmos 139", description: "Honrar pai e mãe, Valor da vida. Dogmas Marianos." },
  { id: 21, title: "10 Mandamentos: 6º e 9º", scripture: "Mt 5,27-28", description: "Castidade e pureza." },
  { id: 22, title: "10 Mandamentos: 7º, 8º e 10º", scripture: "Romanos 13,9", description: "Honestidade e verdade." },
  { id: 23, title: "Intercessão dos Santos", scripture: "Atos 7,52-60", description: "Os santos rezam por nós?" },
  { id: 24, title: "Santos, Heróis da Fé", scripture: "Atos 7,51-60", description: "Exemplos de vida cristã." },
  { id: 25, title: "Os Anjos", scripture: "Apocalipse 12,7-9", description: "Mensageiros e protetores." },
  { id: 26, title: "Espírito Santo: O Dom de Deus", scripture: "Atos 2,1-11", description: "Preparação para a Crisma." },
  { id: 27, title: "Tempo Litúrgico e Natal", scripture: "Lucas 1,30-33", description: "O ano da Igreja." },
  { id: 28, title: "Encontro com Padrinhos", scripture: "Eclesiástico 6,5-17", description: "A importância do padrinho/madrinha." },
  { id: 103, title: "Revisão e Confraternização", scripture: "Efésios 6,1-2", description: "Festa de encerramento", isReview: true },
  { id: 104, title: "Prova Final", scripture: "Efésios 4,32", description: "Teste final para a Crisma", isExam: true },
];

export const INITIAL_USER_STATE: UserState = {
  completedLessonIds: [],
  xp: 0,
  hearts: 5,
  streak: 0,
  lastLessonDate: null,
  currentLessonId: 1,
};
